# Generated by Django 4.0.1 on 2022-01-23 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('years', models.CharField(max_length=4)),
                ('color', models.CharField(choices=[('BLUE', 'Blue'), ('RED', 'Red'), ('PINK', 'Pink'), ('ORANGE', 'Orange'), ('BLACK', 'Black'), ('WHI', 'White'), ('SILVER', 'Silver'), ('BRONZ', 'Brown'), ('YELLOW', 'Yellow'), ('Green', 'Green')], max_length=20)),
                ('reason', models.CharField(choices=[('AIRPORT_TRANSFER', 'Airport pickup and dropoff'), ('RENT_LEASE', 'Rent and Lease'), ('ESCORT', 'Escort and protocol service')], max_length=20)),
                ('category', models.CharField(choices=[('CITY', 'Within the city'), ('OUT_CITY', 'Out of city')], max_length=10)),
                ('type_gear', models.CharField(choices=[('AUTO', 'Automatic transmission'), ('MANUAL', 'Manual transmission'), ('CVT', 'CVT gear'), ('DTC', 'Semi-automatic transmission and DCT dual-clutch transmission')], max_length=10)),
                ('number_seat', models.SmallIntegerField()),
                ('number_door', models.SmallIntegerField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Free'), ('NO_AVAILABLE', 'Unavailable'), ('HIDE', 'Hide')], max_length=12)),
                ('price', models.IntegerField()),
                ('create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
                ('pic_url', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=200)),
                ('verified', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=50)),
                ('promotion_code', models.CharField(max_length=8, unique=True)),
                ('discount_percent', models.FloatField()),
                ('minimum_cost', models.IntegerField()),
                ('expire_day', models.DateTimeField()),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(max_length=20)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('Picked', 'Got the car'), ('Approved', 'Confirm'), ('Denied', 'Refuse'), ('Returned', 'Returned'), ('Pending', 'Pending')], max_length=8)),
                ('total_price', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.car')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('payment_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.payment')),
                ('promotion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='management.promo')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.rent'),
        ),
        migrations.AddField(
            model_name='payment',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
