# Generated by Django 4.0.1 on 2022-01-13 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('years', models.CharField(max_length=4)),
                ('color', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('SUV', 'Sport Utility Vehicle'), ('PPV', 'Pick-Up Passenger Vehicle'), ('MPV', 'Multi Purpose Vehicle'), ('ECO', 'Eco Car'), ('HEV', 'Hybrid Electric Vehicles'), ('EV', 'Electric Vehicles'), ('PU', 'Pick-Up Truck'), ('VAN', 'Van Car'), ('SED', 'Sedan'), ('SUP', 'Supercar'), ('COP', 'Coupe')], max_length=3)),
                ('type_gear', models.CharField(choices=[('AUTO', 'Automatic transmission'), ('MANUAL', 'Manual transmission'), ('CVT', 'CVT gear'), ('DTC', 'Semi-automatic transmission and DCT dual-clutch transmission')], max_length=10)),
                ('number_seat', models.SmallIntegerField()),
                ('number_door', models.SmallIntegerField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Free'), ('NO_AVAILABLE', 'Unavailable'), ('HIDE', 'Hide')], max_length=12)),
                ('price', models.FloatField()),
                ('create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
                ('pic_url', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=50)),
                ('promotion_code', models.CharField(max_length=8, unique=True)),
                ('discount_percent', models.FloatField()),
                ('minimum_cost', models.FloatField()),
                ('expire_day', models.DateTimeField()),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('Picked', 'Got the car'), ('Approved', 'Confirm'), ('Denied', 'Refuse'), ('Returned', 'Returned'), ('Pending', 'Pending')], max_length=8)),
                ('total_price', models.FloatField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.car')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('promotion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='management.promo')),
            ],
        ),
    ]
