# Generated by Django 4.0.1 on 2022-01-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='reason',
            field=models.CharField(choices=[('AIRPORT_TRANSFER', 'Airport pickup and dropoff'), ('RENT_LEASE', 'Rent and Lease'), ('ESCORT', 'Escort and protocol service')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('CITY', 'Within the city'), ('OUT_CITY', 'Out of city')], max_length=10),
        ),
        migrations.AlterField(
            model_name='rent',
            name='total_price',
            field=models.IntegerField(),
        ),
    ]
