# Generated by Django 4.0.1 on 2022-01-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('BLUE', 'Blue'), ('RED', 'Red'), ('PINK', 'Pink'), ('ORANGE', 'Orange'), ('BLACK', 'Black'), ('WHI', 'White'), ('SILVER', 'Silver'), ('BRONZ', 'Brown'), ('YELLOW', 'Yellow'), ('Green', 'Green')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='promo',
            name='minimum_cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rent',
            name='total_price',
            field=models.IntegerField(),
        ),
    ]
